import { HiringRunRecord } from "@/lib/types";

export const demoRunId = "demo-sales-engineer-2025";

export const demoRun: HiringRunRecord = {
  id: demoRunId,
  title: "Senior Sales Engineer",
  job_description:
    "Lead technical discovery, solution design, demos, and enterprise proof-of-value motions for a B2B SaaS platform. Partner with account executives, influence procurement stakeholders, and translate customer pain into technical business cases.",
  hiring_context:
    "High-growth scale-up. The team needs stronger enterprise deal support, sharper stakeholder mapping, and candidates who can handle discovery, technical depth, and cross-functional collaboration without long ramp time.",
  company_priority: "Enterprise solution selling with technical credibility",
  must_have_skills: [
    "Solution Selling",
    "Enterprise SaaS",
    "Technical Discovery",
    "Stakeholder Management",
    "Communication",
  ],
  nice_to_have_skills: ["CRM", "Negotiation", "Product Knowledge", "Demo Design", "Prospecting"],
  candidates: [
    {
      name: "Neha Bansal",
      resume_text: "8 years across enterprise SaaS, solution consulting, and strategic pre-sales. Led multi-stakeholder demos and complex evaluations.",
      professional_links: {
        github: null,
        portfolio: "Selected solution demo narratives and customer rollout summaries.",
        linkedin: "Strong enterprise pre-sales background",
      },
      notes: "High-confidence enterprise seller with consistent references.",
    },
    {
      name: "Rohan Mehta",
      resume_text: "7 years in sales engineering and technical account strategy across cloud platforms and CRM-heavy sales cycles.",
      professional_links: {
        portfolio: "Deal architecture playbooks and workshop outcomes.",
        linkedin: "Enterprise sales engineering profile",
      },
    },
    {
      name: "Aisha Khan",
      resume_text: "5 years blending product consulting, demos, and customer education for mid-market and enterprise teams.",
      professional_links: {
        portfolio: "Enablement and customer workshop case studies",
        linkedin: "Customer-facing solutions specialist",
      },
    },
    {
      name: "Karan Verma",
      resume_text: "Technically strong solutions consultant with SaaS implementation exposure and early-stage enterprise selling work.",
      professional_links: {
        linkedin: "Solutions consultant",
      },
    },
    {
      name: "Priya Iyer",
      resume_text: "Strong communicator with product presentation skills and some account support experience in B2B sales teams.",
      professional_links: null,
    },
  ],
  status: "completed",
  created_at: "2026-05-25T12:00:00.000Z",
  results: {
    run_id: demoRunId,
    status: "completed",
    report: "Evidence-backed shortlist generated from orchestrated multi-agent evaluation.",
    pipeline: [
      {
        stage: "JD Deconstruction Agent",
        status: "completed",
        summary: "Role, skills, responsibilities, and weighting rubric extracted from job description.",
        raw_output: {
          role_title: "Senior Sales Engineer",
          seniority: "senior",
          must_have_skills: ["Solution Selling", "Enterprise SaaS", "Technical Discovery", "Stakeholder Management", "Communication"],
          nice_to_have_skills: ["CRM", "Negotiation", "Product Knowledge", "Demo Design", "Prospecting"],
          responsibilities: ["Run discovery", "Lead demos", "Support enterprise deals"],
          domain_requirements: ["B2B SaaS", "Enterprise sales cycles"],
          red_flags: ["No proof of deal support", "Weak customer-facing evidence"],
          recommended_weights: {
            requirement_match: 35,
            evidence_strength: 25,
            professional_footprint: 20,
            hiring_context_fit: 15,
            risk_penalty: 5,
          },
        },
      },
      {
        stage: "Hiring Context Agent",
        status: "completed",
        summary: "Team gaps and success signals mapped to hiring context.",
        raw_output: {
          team_gaps: ["Enterprise deal ownership", "Stakeholder mapping", "Technical objection handling"],
          company_priorities: ["Fast ramp time", "Credible demo leadership", "Cross-functional collaboration"],
          ideal_candidate_traits: ["Executive presence", "Structured discovery", "Customer influence"],
          context_fit_keywords: ["enterprise", "saas", "stakeholder", "discovery", "technical depth"],
          context_risks: ["Candidates from only support-heavy roles may underfit"],
        },
      },
      {
        stage: "Resume Parsing Agent",
        status: "completed",
        summary: "Core candidate chronology, skills, and links normalized.",
        raw_output: { candidate_count: 5, parsed_sections: ["experience", "skills", "projects", "links"] },
      },
      {
        stage: "Candidate Evidence Agent",
        status: "completed",
        summary: "Verifiable evidence extracted from resumes and profile summaries.",
        raw_output: { evidence_items: 27, unsupported_claims: 4, confidence_distribution: { high: 15, medium: 9, low: 3 } },
      },
      {
        stage: "Transferable Skill Agent",
        status: "completed",
        summary: "Adjacent skills translated into role-relevant matches where direct evidence was partial.",
        raw_output: { exact_matches: 16, transferable_matches: 8, missing_requirements: 5 },
      },
      {
        stage: "Professional Footprint Agent",
        status: "completed",
        summary: "Portfolio and profile evidence checked for claim support and signal strength.",
        raw_output: { profiles_reviewed: 4, neutral_profiles: 1, unsupported_claims: 2 },
      },
      {
        stage: "Risk & Contradiction Agent",
        status: "completed",
        summary: "Key uncertainties and interview verification areas identified.",
        raw_output: { low_risk: 2, medium_risk: 2, high_risk: 1 },
      },
      {
        stage: "Score Aggregation Engine",
        status: "completed",
        summary: "Weighted scoring executed in backend code using structured agent outputs.",
        raw_output: { scoring_formula: "0.35*requirement + 0.25*evidence + 0.20*footprint + 0.15*context - risk" },
      },
      {
        stage: "Hiring Panel Review Agent",
        status: "completed",
        summary: "Simulated panel perspectives generated for top candidates and risk cases.",
        raw_output: { panelists: ["Technical Lead", "HR Recruiter", "Hiring Manager", "Risk Auditor"] },
      },
      {
        stage: "Interview Pack Generator Agent",
        status: "completed",
        summary: "Structured technical, behavioral, and risk-validation questions prepared.",
        raw_output: { technical_questions: 12, behavioral_questions: 8, risk_validation_questions: 7 },
      },
      {
        stage: "Final Shortlist Report Agent",
        status: "completed",
        summary: "Final narrative, top 5 rationale, and interview focus areas assembled.",
        raw_output: { report_ready: true, top_candidates: 5 },
      },
    ],
    top_candidates: [
      {
        rank: 1,
        candidate_name: "Neha Bansal",
        status: "completed",
        final_score: 92,
        recommendation: "Strong Shortlist",
        score_breakdown: {
          requirement_match: 94,
          evidence_strength: 91,
          professional_footprint: 88,
          hiring_context_fit: 93,
          risk_penalty: 2,
          final_score: 92,
          recommendation: "Strong Shortlist",
          score_explanation: "Consistent enterprise SaaS evidence, strong stakeholder mapping, and low verification risk.",
        },
        top_strengths: ["Solution Selling", "SaaS", "Negotiation"],
        key_risks: ["Minimal gaps"],
        why: "Outstanding solution-selling and stakeholder management; proven impact in similar market.",
      },
      {
        rank: 2,
        candidate_name: "Rohan Mehta",
        status: "completed",
        final_score: 87,
        recommendation: "Strong Shortlist",
        score_breakdown: {
          requirement_match: 89,
          evidence_strength: 88,
          professional_footprint: 84,
          hiring_context_fit: 90,
          risk_penalty: 3,
          final_score: 87,
          recommendation: "Strong Shortlist",
          score_explanation: "Strong technical discovery depth and enterprise references with slightly narrower vertical breadth.",
        },
        top_strengths: ["Enterprise Sales", "Stakeholder Mgmt", "CRM"],
        key_risks: ["Reference depth to verify"],
        why: "Excellent technical depth and discovery skills; strong enterprise references.",
      },
      {
        rank: 3,
        candidate_name: "Aisha Khan",
        status: "completed",
        final_score: 82,
        recommendation: "Shortlist",
        score_breakdown: {
          requirement_match: 84,
          evidence_strength: 83,
          professional_footprint: 79,
          hiring_context_fit: 84,
          risk_penalty: 3,
          final_score: 82,
          recommendation: "Shortlist",
          score_explanation: "Balanced customer-facing strength and collaboration evidence with slightly lighter enterprise depth.",
        },
        top_strengths: ["Account Mgmt", "Communication", "Product Knowledge"],
        key_risks: ["Skill depth"],
        why: "Consistent track record of closing complex deals; great cross-functional collaboration.",
      },
      {
        rank: 4,
        candidate_name: "Karan Verma",
        status: "completed",
        final_score: 76,
        recommendation: "Shortlist",
        score_breakdown: {
          requirement_match: 78,
          evidence_strength: 75,
          professional_footprint: 72,
          hiring_context_fit: 77,
          risk_penalty: 4,
          final_score: 76,
          recommendation: "Shortlist",
          score_explanation: "Technical credibility is clear but enterprise sales ownership evidence is still developing.",
        },
        top_strengths: ["Prospecting", "CRM", "Email Outreach"],
        key_risks: ["Experience depth"],
        why: "Good technical skills; limited experience in enterprise sales cycles.",
      },
      {
        rank: 5,
        candidate_name: "Priya Iyer",
        status: "completed",
        final_score: 71,
        recommendation: "Shortlist",
        score_breakdown: {
          requirement_match: 73,
          evidence_strength: 70,
          professional_footprint: 50,
          hiring_context_fit: 74,
          risk_penalty: 4,
          final_score: 71,
          recommendation: "Shortlist",
          score_explanation: "Clear communication and presentation evidence, but limited external professional footprint and lighter enterprise ownership.",
        },
        top_strengths: ["Research", "Communication", "Presentation"],
        key_risks: ["Tenure consistency"],
        why: "Strong communicator; need to validate enterprise deal ownership.",
      },
    ],
    report_data: {
      summary: "Jobest recommends a focused shortlist led by candidates with proven enterprise solution-selling depth and strong stakeholder management.",
      job_summary:
        "Senior Sales Engineer role focused on technical discovery, enterprise demos, and supporting complex SaaS deals with credible business and product storytelling.",
      hiring_context_summary:
        "The team is closing a gap in enterprise deal support and needs candidates who can influence stakeholders, handle objections, and ramp quickly in a high-growth environment.",
      top_5_summary:
        "The shortlist prioritizes evidence-backed solution selling, cross-functional collaboration, and professional signals that support enterprise-readiness.",
      candidate_explanations: [
        { candidate_name: "Neha Bansal", explanation: "Best overall fit with strong end-to-end sales execution, technical credibility, and executive storytelling." },
        { candidate_name: "Rohan Mehta", explanation: "Excellent discovery skills and technical depth with strong enterprise references." },
        { candidate_name: "Aisha Khan", explanation: "Balanced candidate with strong customer-facing collaboration and product fluency." },
        { candidate_name: "Karan Verma", explanation: "Technically credible but needs deeper verification of enterprise sales ownership." },
        { candidate_name: "Priya Iyer", explanation: "Promising communicator whose deal ownership and external professional signals need validation." },
      ],
      risks_to_verify: ["Enterprise deal ownership depth", "Handling long sales cycles", "Technical objection handling confidence"],
      final_recommendation: "Proceed with the top 3 immediately and use structured interview packs to validate risk areas for ranks 4 and 5.",
      suggested_next_action: "Run structured hiring panel interviews this week and compare on a shared rubric.",
      top_candidates: [],
    },
    candidates: [
      {
        candidate: {
          name: "Neha Bansal",
          resume_text: "Led enterprise technical sales motions across SaaS accounts with strong solution design and procurement alignment.",
          professional_links: {
            portfolio: "Demo narratives, evaluation plans, customer workshop outputs.",
            linkedin: "Senior sales engineer profile",
          },
        },
        status: "completed",
        parsed_profile: {
          candidate_name: "Neha Bansal",
          education: [{ degree: "B.Tech", field: "Computer Science" }],
          work_experience: [{ role: "Senior Sales Engineer", duration: "4 years" }],
          skills: ["Solution Selling", "Enterprise SaaS", "Negotiation", "Stakeholder Management"],
          tools: ["CRM", "Demo tooling", "Analytics"],
          certifications: ["AWS Cloud Practitioner"],
          achievements: ["Increased enterprise win rate in strategic accounts"],
          professional_links: ["portfolio", "linkedin"],
        },
        evidence: {
          evidence_items: [
            { skill: "Solution Selling", evidence: "Led end-to-end technical discovery and executive demos for enterprise SaaS deals.", source: "resume", confidence: "high" },
            { skill: "Stakeholder Management", evidence: "Mapped technical and procurement stakeholders across 6-figure evaluations.", source: "resume", confidence: "high" },
            { skill: "Negotiation", evidence: "Supported commercial and technical alignment during proof-of-value phase.", source: "profile", confidence: "medium" },
          ],
          unsupported_claims: [],
        },
        transferable_skills: {
          exact_matches: [
            { requirement: "Solution Selling", candidate_skill: "Solution Selling", evidence: "Strategic demos", confidence: "high" },
            { requirement: "Stakeholder Management", candidate_skill: "Stakeholder Management", evidence: "Enterprise stakeholder maps", confidence: "high" },
            { requirement: "Communication", candidate_skill: "Executive storytelling", evidence: "Board-ready readouts", confidence: "high" },
          ],
          transferable_matches: [{ requirement: "Technical Discovery", candidate_skill: "Customer workshop facilitation", evidence: "Discovery workshops", reasoning: "Adjacent discovery rigor", confidence: "medium" }],
          missing_requirements: [],
        },
        professional_footprint: {
          portfolio_score: 89,
          github_score: 66,
          claim_support: "strong",
          professional_evidence: ["Portfolio contains solution workshop summaries", "Professional profile supports enterprise pre-sales depth"],
          concerns: ["GitHub is not central to role but limited code depth is acceptable"],
          supported_resume_claims: ["Solution Selling", "Stakeholder Management"],
          unsupported_resume_claims: [],
        },
        risk_audit: {
          risk_level: "low",
          risk_penalty: 2,
          risks: ["Minimal gaps"],
          recommended_interview_focus: ["Complex deal example", "Executive objection handling"],
        },
        score: {
          requirement_match: 94,
          evidence_strength: 91,
          professional_footprint: 88,
          hiring_context_fit: 93,
          risk_penalty: 2,
          final_score: 92,
          recommendation: "Strong Shortlist",
          score_explanation: "Strong enterprise evidence across solution selling, stakeholder alignment, and fast-ramp context fit.",
        },
        panel_review: {
          technical_lead_view: "Credible in solution architecture tradeoffs and technical discovery.",
          hr_recruiter_view: "Trajectory is coherent and customer-facing communication is strong.",
          hiring_manager_view: "Low-ramp candidate who can raise enterprise deal quality quickly.",
          risk_auditor_view: "Only minor verification needed on most complex late-stage deals.",
          final_panel_recommendation: "Proceed immediately to final panel.",
        },
        interview_pack: {
          technical_questions: [{ question: "Walk us through a complex solution demo you tailored for multiple stakeholders.", what_to_listen_for: "Discovery logic, tradeoffs, stakeholder tailoring" }],
          behavioral_questions: [{ question: "Describe a time you rescued a deal that was technically misaligned.", what_to_listen_for: "Ownership, influence, alignment under pressure" }],
          risk_validation_questions: [{ question: "Which part of enterprise procurement slows deals most, and how have you mitigated it?", what_to_listen_for: "Specific operational experience" }],
        },
        why_this_candidate: "Neha combines enterprise storytelling with verifiable technical deal support and low execution risk.",
        why_not_this_candidate: "GitHub/code footprint is lighter than a solutions architect profile, though that is not central for this role.",
      },
      {
        candidate: {
          name: "Rohan Mehta",
          resume_text: "Enterprise sales engineer with strong technical account strategy and workshop leadership.",
          professional_links: {
            portfolio: "Discovery decks and CRM transformation examples",
            linkedin: "Sales engineer",
          },
        },
        status: "completed",
        parsed_profile: {
          candidate_name: "Rohan Mehta",
          skills: ["Enterprise SaaS", "Technical Discovery", "CRM", "Stakeholder Management"],
          tools: ["CRM", "Data visualization"],
          achievements: ["Supported expansion into strategic accounts"],
          professional_links: ["portfolio", "linkedin"],
        },
        evidence: {
          evidence_items: [
            { skill: "Technical Discovery", evidence: "Led technical scoping workshops before enterprise rollout.", source: "resume", confidence: "high" },
            { skill: "CRM", evidence: "Designed process mapping around CRM-driven sales operations.", source: "profile", confidence: "medium" },
          ],
          unsupported_claims: [{ claim: "Global procurement leadership", reason: "Breadth implied but not clearly evidenced" }],
        },
        transferable_skills: {
          exact_matches: [{ requirement: "Technical Discovery", candidate_skill: "Technical Discovery", evidence: "Scoping workshops", confidence: "high" }],
          transferable_matches: [{ requirement: "Negotiation", candidate_skill: "Cross-functional alignment", evidence: "Strategic planning", reasoning: "Adjacent commercial influence", confidence: "medium" }],
          missing_requirements: [],
        },
        professional_footprint: {
          portfolio_score: 84,
          github_score: 58,
          claim_support: "moderate",
          professional_evidence: ["Portfolio shows structured discovery artifacts"],
          concerns: ["Need clearer evidence of late-stage negotiation ownership"],
          supported_resume_claims: ["Technical Discovery", "CRM"],
          unsupported_resume_claims: ["Global procurement leadership"],
        },
        risk_audit: {
          risk_level: "low",
          risk_penalty: 3,
          risks: ["Reference depth to verify"],
          recommended_interview_focus: ["Negotiation ownership", "Late-stage executive alignment"],
        },
        score: {
          requirement_match: 89,
          evidence_strength: 88,
          professional_footprint: 84,
          hiring_context_fit: 90,
          risk_penalty: 3,
          final_score: 87,
          recommendation: "Strong Shortlist",
          score_explanation: "High discovery rigor and strong enterprise motion support, with only moderate uncertainty around final-stage commercial ownership.",
        },
        panel_review: {
          technical_lead_view: "Strong technical workshop discipline.",
          hr_recruiter_view: "Cohesive customer-facing narrative with good progression.",
          hiring_manager_view: "Likely high-impact candidate with fast ramp potential.",
          risk_auditor_view: "Validate ownership claims in negotiation-heavy deals.",
          final_panel_recommendation: "Advance to panel with targeted ownership questions.",
        },
        interview_pack: {
          technical_questions: [{ question: "How do you structure a discovery process for a technically complex buyer?", what_to_listen_for: "Hypothesis, sequencing, stakeholder handling" }],
          behavioral_questions: [{ question: "Tell us about a deal where you influenced without direct commercial authority.", what_to_listen_for: "Influence and collaboration" }],
          risk_validation_questions: [{ question: "What part of negotiations did you personally own?", what_to_listen_for: "Specific, evidence-backed ownership" }],
        },
        why_this_candidate: "Rohan is one of the strongest context-fit profiles for enterprise discovery and stakeholder orchestration.",
        why_not_this_candidate: "Need to verify whether negotiation and procurement influence was direct or supporting.",
      },
      {
        candidate: {
          name: "Aisha Khan",
          resume_text: "Solutions specialist with strong customer education, demo, and product communication skills.",
          professional_links: {
            portfolio: "Workshop case studies",
            linkedin: "Solutions specialist",
          },
        },
        status: "completed",
        parsed_profile: {
          candidate_name: "Aisha Khan",
          skills: ["Communication", "Product Knowledge", "Account Management"],
          tools: ["Presentation tools", "CRM"],
          achievements: ["Improved demo-to-opportunity conversion"],
        },
        evidence: {
          evidence_items: [
            { skill: "Communication", evidence: "Led product workshops and post-demo alignment sessions.", source: "resume", confidence: "high" },
            { skill: "Product Knowledge", evidence: "Created product narratives for multi-team onboarding.", source: "profile", confidence: "medium" },
          ],
          unsupported_claims: [],
        },
        transferable_skills: {
          exact_matches: [{ requirement: "Communication", candidate_skill: "Communication", evidence: "Workshop facilitation", confidence: "high" }],
          transferable_matches: [
            { requirement: "Solution Selling", candidate_skill: "Product consulting", evidence: "Customer education", reasoning: "Adjacent to pre-sales solutioning", confidence: "medium" },
            { requirement: "Stakeholder Management", candidate_skill: "Cross-functional coordination", evidence: "Product and customer teams", reasoning: "Relevant stakeholder collaboration", confidence: "medium" },
          ],
          missing_requirements: [{ requirement: "Enterprise SaaS", reason: "Direct large-account evidence is lighter than top 2 candidates." }],
        },
        professional_footprint: {
          portfolio_score: 79,
          github_score: 50,
          claim_support: "moderate",
          professional_evidence: ["Portfolio shows workshop and enablement depth"],
          concerns: ["Direct enterprise deal ownership is not as explicit"],
          supported_resume_claims: ["Communication", "Product Knowledge"],
          unsupported_resume_claims: [],
        },
        risk_audit: {
          risk_level: "medium",
          risk_penalty: 3,
          risks: ["Skill depth"],
          recommended_interview_focus: ["Enterprise pressure handling", "Late-stage objections"],
        },
        score: {
          requirement_match: 84,
          evidence_strength: 83,
          professional_footprint: 79,
          hiring_context_fit: 84,
          risk_penalty: 3,
          final_score: 82,
          recommendation: "Shortlist",
          score_explanation: "Strong collaboration and customer-facing evidence, but enterprise scale and deal depth need confirmation.",
        },
        panel_review: {
          technical_lead_view: "Good communicator with enough product fluency for customer conversations.",
          hr_recruiter_view: "Profile is coherent and marketable.",
          hiring_manager_view: "Could succeed with support; not the strongest direct enterprise proof.",
          risk_auditor_view: "Verify complex objection handling under executive scrutiny.",
          final_panel_recommendation: "Shortlist with targeted enterprise-depth validation.",
        },
        interview_pack: {
          technical_questions: [{ question: "How do you handle a technical objection when you are not the deepest product expert in the room?", what_to_listen_for: "Structure, honesty, influence" }],
          behavioral_questions: [{ question: "Describe a time you aligned product and sales around a difficult customer need.", what_to_listen_for: "Collaboration and execution" }],
          risk_validation_questions: [{ question: "Give an example of leading a late-stage enterprise objection conversation.", what_to_listen_for: "Specificity and direct ownership" }],
        },
        why_this_candidate: "Aisha brings balanced customer communication, workshop facilitation, and cross-functional alignment.",
        why_not_this_candidate: "Compared with the top two, her direct enterprise deal ownership is less explicit.",
      },
      {
        candidate: {
          name: "Karan Verma",
          resume_text: "Solutions consultant with technical product depth and some early enterprise exposure.",
          professional_links: {
            linkedin: "Solutions consultant",
          },
        },
        status: "completed",
        parsed_profile: {
          candidate_name: "Karan Verma",
          skills: ["Prospecting", "CRM", "Technical Communication"],
          tools: ["CRM", "Email outreach tools"],
        },
        evidence: {
          evidence_items: [
            { skill: "Technical Communication", evidence: "Explained implementation tradeoffs to customer teams.", source: "resume", confidence: "medium" },
            { skill: "CRM", evidence: "Maintained opportunity context and follow-up notes.", source: "resume", confidence: "medium" },
          ],
          unsupported_claims: [{ claim: "Enterprise deal lead", reason: "Worked on enterprise accounts but ownership level is unclear." }],
        },
        transferable_skills: {
          exact_matches: [{ requirement: "Communication", candidate_skill: "Technical Communication", evidence: "Customer explanation", confidence: "medium" }],
          transferable_matches: [{ requirement: "Technical Discovery", candidate_skill: "Implementation scoping", evidence: "Scoping sessions", reasoning: "Adjacent workflow", confidence: "medium" }],
          missing_requirements: [{ requirement: "Solution Selling", reason: "Customer-facing selling proof remains partial." }],
        },
        professional_footprint: {
          portfolio_score: 68,
          github_score: 50,
          claim_support: "neutral",
          professional_evidence: ["LinkedIn suggests relevant domain exposure"],
          concerns: ["Few deep external artifacts"],
          supported_resume_claims: ["CRM", "Technical Communication"],
          unsupported_resume_claims: ["Enterprise deal lead"],
        },
        risk_audit: {
          risk_level: "medium",
          risk_penalty: 4,
          risks: ["Experience depth"],
          recommended_interview_focus: ["Sales ownership", "Executive presence"],
        },
        score: {
          requirement_match: 78,
          evidence_strength: 75,
          professional_footprint: 72,
          hiring_context_fit: 77,
          risk_penalty: 4,
          final_score: 76,
          recommendation: "Shortlist",
          score_explanation: "Promising technical fit, but the strongest risks are around direct selling ownership and enterprise maturity.",
        },
        panel_review: {
          technical_lead_view: "Technically sound enough for solution conversations.",
          hr_recruiter_view: "Marketable background but not fully proven for this seniority.",
          hiring_manager_view: "Could work if we accept more ramp and coaching.",
          risk_auditor_view: "Need precise ownership validation before advancing too far.",
          final_panel_recommendation: "Keep in the shortlist but probe ownership hard.",
        },
        interview_pack: {
          technical_questions: [{ question: "What is the hardest technical objection you handled, and what did you do next?", what_to_listen_for: "Direct handling versus escalation" }],
          behavioral_questions: [{ question: "Describe a time you had to win trust quickly in a customer meeting.", what_to_listen_for: "Presence and adaptability" }],
          risk_validation_questions: [{ question: "Which parts of an enterprise cycle did you own directly?", what_to_listen_for: "Concrete ownership boundaries" }],
        },
        why_this_candidate: "Karan brings technical fluency and solid customer support instincts.",
        why_not_this_candidate: "The role may stretch him on enterprise ownership and late-stage solution selling.",
      },
      {
        candidate: {
          name: "Priya Iyer",
          resume_text: "Customer-facing communicator with presentation strength and some B2B sales support exposure.",
          professional_links: null,
        },
        status: "completed",
        parsed_profile: {
          candidate_name: "Priya Iyer",
          skills: ["Communication", "Presentation", "Research"],
          tools: ["Slides", "CRM"],
        },
        evidence: {
          evidence_items: [
            { skill: "Communication", evidence: "Ran customer-facing presentations and internal training sessions.", source: "resume", confidence: "high" },
            { skill: "Research", evidence: "Prepared account research briefs and meeting prep materials.", source: "resume", confidence: "medium" },
          ],
          unsupported_claims: [{ claim: "Enterprise deal ownership", reason: "No strong evidence beyond support tasks." }],
        },
        transferable_skills: {
          exact_matches: [{ requirement: "Communication", candidate_skill: "Communication", evidence: "Presentations", confidence: "high" }],
          transferable_matches: [{ requirement: "Stakeholder Management", candidate_skill: "Meeting coordination", evidence: "Cross-team prep", reasoning: "Partial coordination exposure", confidence: "low" }],
          missing_requirements: [{ requirement: "Solution Selling", reason: "No direct evidence of discovery-to-close support at enterprise depth." }],
        },
        professional_footprint: {
          portfolio_score: 50,
          github_score: 50,
          claim_support: "unavailable",
          professional_evidence: [],
          concerns: ["No external professional evidence submitted; treated as neutral, not negative"],
          supported_resume_claims: ["Communication"],
          unsupported_resume_claims: ["Enterprise deal ownership"],
        },
        risk_audit: {
          risk_level: "high",
          risk_penalty: 4,
          risks: ["Tenure consistency", "Enterprise ownership unclear"],
          recommended_interview_focus: ["Ownership boundaries", "Customer influence under pressure"],
        },
        score: {
          requirement_match: 73,
          evidence_strength: 70,
          professional_footprint: 50,
          hiring_context_fit: 74,
          risk_penalty: 4,
          final_score: 71,
          recommendation: "Shortlist",
          score_explanation: "Communication is a real strength, but the absence of stronger selling evidence and professional footprint keeps confidence lower.",
        },
        panel_review: {
          technical_lead_view: "Not the deepest technical seller in the pool.",
          hr_recruiter_view: "Strong presenter with a polished customer-facing style.",
          hiring_manager_view: "Could be a stretch unless the role is more enablement-heavy than stated.",
          risk_auditor_view: "Neutral professional footprint is acceptable, but direct ownership remains unclear.",
          final_panel_recommendation: "Borderline shortlist if we need communication-first options.",
        },
        interview_pack: {
          technical_questions: [{ question: "How have you translated technical complexity into customer-facing business value?", what_to_listen_for: "Clarity and business linkage" }],
          behavioral_questions: [{ question: "Tell us about a high-stakes customer presentation and how you prepared for it.", what_to_listen_for: "Preparation and influence" }],
          risk_validation_questions: [{ question: "What did you personally own in your largest B2B opportunity?", what_to_listen_for: "Specificity and honesty" }],
        },
        why_this_candidate: "Priya offers polished communication and presentation confidence that could help in customer-facing scenarios.",
        why_not_this_candidate: "Relative to stronger peers, the role-critical enterprise solution-selling evidence is still limited.",
      },
    ],
  },
};
